name: shopping_list
description: "Android and IOS application for creating shopping lists."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+7

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.27.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  provider: ^6.1.2
  wakelock_plus: ^1.2.9
  tutorial_coach_mark: ^1.2.12
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true